# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keylatch < Formula
  desc "Zero-trust credential vault CLI for AI-assisted workflows"
  homepage "https://github.com/keylatch/keylatch"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keylatch/keylatch/releases/download/v0.9.0/keylatch_0.9.0_darwin_amd64.tar.gz"
      sha256 "f346d4dfa24a4bd674277156560d84714fe50b56c4f93e4c4ebf2f802a5ff359"

      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keylatch/keylatch/releases/download/v0.9.0/keylatch_0.9.0_darwin_arm64.tar.gz"
      sha256 "fa3ae9bd2346ad81618e563e69efa8d4a9a4c7637251e7e178f54b1b430f5b43"

      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keylatch/keylatch/releases/download/v0.9.0/keylatch_0.9.0_linux_amd64.tar.gz"
      sha256 "a39bf3891dc846b7b2775b8985f30dc0cda8b1d34d56e97e88cdde16334f41d3"
      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keylatch/keylatch/releases/download/v0.9.0/keylatch_0.9.0_linux_arm64.tar.gz"
      sha256 "0632148556927cd355bdc2a89ccb66d82b43213368790c2eb3a3ddfb10bfa635"
      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
  end

  test do
    system "#{bin}/keylatch", "--version"
  end
end
