# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keylatch < Formula
  desc "Zero-trust credential vault CLI for AI-assisted workflows"
  homepage "https://github.com/keylatch/keylatch"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keylatch/keylatch/releases/download/v1.0.0/keylatch_1.0.0_darwin_amd64.tar.gz"
      sha256 "7ccdbdcc8536168b53e052bb744c67d7197cf0725907858d784498d02915a133"

      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keylatch/keylatch/releases/download/v1.0.0/keylatch_1.0.0_darwin_arm64.tar.gz"
      sha256 "4366ef6dacc727bf2e11a446ba6108ec37cf5b0921233f136d8f1d68aa17291c"

      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keylatch/keylatch/releases/download/v1.0.0/keylatch_1.0.0_linux_amd64.tar.gz"
      sha256 "7778a22865f0d9c0640c73e9d644e3a5687492e4706f999c201f12bae308e953"
      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keylatch/keylatch/releases/download/v1.0.0/keylatch_1.0.0_linux_arm64.tar.gz"
      sha256 "1a06c5e3b04072ec70a48bc823dea35ff7c3e145e8e7bd559da058206f4c7acd"
      define_method(:install) do
        bin.install "keylatch"
        generate_completions_from_executable(bin/"keylatch", "completion")
      end
    end
  end

  test do
    system "#{bin}/keylatch", "--version"
  end
end
